export const Cars = {
  Toyota: ["Camry", "Corolla", "Highlander"],
  Ford: ["Edge", "Escape", "Focus"],
  Honda: ["Accord", "Civic"],
};

export const Camry = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 1,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSicayxK-zSQKO2q0gvy_27RbfYY7aOhLUtQ&usqp=CAU",
  },

  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 2,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT49kT1efPvyvHqPRVaoF67NhM3r4u1geV1Wg&usqp=CAU",
  },

  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 3,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQle3P7smI3CT9kV4U5tW_g_5hh1F1GAXvcEA&usqp=CAU",
  },
];

export const Corolla = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 4,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://media.ed.edmunds-media.com/toyota/corolla/2023/fe/2023_toyota_corolla_f34_fe_113221_1280.jpg",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 5,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://www.autotrader.com/wp-content/uploads/2021/04/2021-toyota-corolla-le-front-right-side.jpg",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 6,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSicayxK-zSQKO2q0gvy_27RbfYY7aOhLUtQ&usqp=CAU",
  },
];

export const Highlander = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 7,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe1LVQ7PjRZkFKJf7j0Tqjjkv28LIwGQwM6g&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 8,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ70vThZMqI_ytyQybTNlMKgeuNsaMPB_sXiw&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 9,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuIdDrazzf1HFI-jry70hykQMGcqzVPvtaMA&usqp=CAU",
  },
];

export const Edge = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 10,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGtmg7LO-nclBf70i3NRI8L3A2Jd3Er2mY7A&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 11,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN7VJ6vdwOr_mj4F-wiHA27mRQCO6TzKjNYQ&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 12,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpDwxL36sdJHD6Sjezto7EUiqH0qiHEUwKRg&usqp=CAU",
  },
];

export const Escape = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 13,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6RmPld-WQL5lWYJBIWATiY-cZ1r2HIWsPWw&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 14,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpga0zrnowLo4m7rAgO8_eNnDxLi2gmux_1Q&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 15,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4IMpbxGhCr2hRgneq-AxKihclKtmOPSLtOw&usqp=CAU",
  },
];

export const Focus = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 16,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaEBmWJ-5A60MH0M66UvGmjcNlJ_kJY8U5gg&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 17,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR41ZmCniMUJ8TwIytlX1ppJDuHn1sb0V7MA&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 18,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuZcrJHbnbfJj6HjavEh_O90Gd7w7Equv7rA&usqp=CAU",
  },
];

export const Accord = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 19,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwedwkiaRnSuprUEGiXtz_tkcXCCQx46a6dA&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 20,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxQ_W0mvJEW1DXrY__ZUxUsnRrrkEsz4t36w&usqp=CAU",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 21,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSztuIrP17luabwqTyOLiEnebOChRs2ME6jBQ&usqp=CAU",
  },
];

export const Civic = [
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 22,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://www.autotrader.com/wp-content/uploads/2020/08/2021-honda-civic-hatchback-front-left-side.jpg",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 23,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://www.motortrend.com/uploads/2021/11/2022-Honda-Civic-Hatchback-Sport-Touring-22.jpg",
  },
  {
    Name: "2007 Camry",
    Color: "Brown",
    Interior: "Leather",
    Drive: "FWD",
    Trans: "Automatic",
    VIN: 24,
    Engine: "XXX",
    Mileage: 125000,
    Stock: 25,
    IMG: "https://www.topgear.com/sites/default/files/cars-car/image/2020/09/308395_2020_civic_type_r_mmc_launch.jpg",
  },
];
